services:
  redis:
    image: redis:8.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  redisinsight:
    image: redis/redisinsight:2.70.0
    depends_on:
      - redis
    ports:
      - '5540:5540'
    volumes:
      - 'redisinsight_data:/data'

volumes:
  redis_data:
    driver: local

  redisinsight_data:
    driver: local
