services:
  app:
    profiles: ["app"]
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - PHX_HOST=${PHX_HOST:-localhost}
      - PORT=4000
      - REDIS_PRIVATE_URL=redis://redis:6379/0
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-dev_only_secret_key_base_not_for_production}
      - SENTRY_DSN=${SENTRY_DSN:-https://fake@sentry.io/1}
      - PUSHOVER_ENABLED=${PUSHOVER_ENABLED:-false}

  redis:
    image: redis:8.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  redisinsight:
    image: redis/redisinsight:2.70.0
    depends_on:
      - redis
    ports:
      - '5540:5540'
    volumes:
      - 'redisinsight_data:/data'

volumes:
  redis_data:
    driver: local

  redisinsight_data:
    driver: local
